### ISSUE TITLE
Formular um MongoDB über Code zu füllen

### ISSUE THREAD

**Issue by mportz** [yuayixio/aufklaerwerk-vue#15]
Wir wollen Organisationen/Angebote über eine UI in die DB hinzufügen können. Dafür müssen wir die /add API Methode so umschreiben, dass alle Felder, die benötigt werden, in die DB geschrieben werden.

**Comment by Schuetzlito** [comment]
ist erledigt. Aufrufbar über die webseite mit /admin am Ende.
