### ISSUE TITLE
Footer links funtionieren nicht wie gewollt

### ISSUE THREAD

**Issue by mportz** [yuayixio/aufklaerwerk-vue#17]

**Comment by felixhasse** [comment]
Problem war, dass der Server die Unterseiten nicht gefunden hat, weil nicht für jede Seite eine HTML-Datei existiert. Kann dadurch gelöst werden, dass eine _redirects Datei im Public-Ordner erstellt wird, die alle URLs auf index.html umleitet.
Siehe hier: https://router.vuejs.org/guide/essentials/history-mode.html#netlify

**Comment by mportz** [comment]
Top! Ich ändere das auch mal noch für den dev branch :)

**Comment by mportz** [comment]
Sollen wir das auf dem dev noch nachziehen?
