### ISSUE TITLE
scaling on mobile devices

### ISSUE THREAD

**Issue by mportz** [yuayixio/aufklaerwerk-vue#47]
Wenn man die Website mit einem Mobilgerät aufruft und rauszoomt, wird die Seite nicht gut skaliert, das Hintergrund Bild wird kleiner: 
![image](https://user-images.githubusercontent.com/74604123/196465972-3598b65d-7e61-46ca-9775-2598a3b517b3.png)

**Comment by JuliaButte** [comment]
Wird mit Issue 20 überarbeitet.
